apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-appli

spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-appli

  template:
    metadata:
      labels:
        app: mon-appli
spec:
  containers:
  - name: mon-appli
    image: abdo030/mon-image:2
    ports:
    - containerPort: 80  # تغيير من 3001 أو غيره إلى 80