apiVersion: v1
kind: Service
metadata:
  name: mon-appli-service
spec:
  selector:
    app: mon-appli
  ports:
    - protocol: TCP
      port: 80         # المنفذ الخارجي للخدمة
      targetPort: 80   # المنفذ الداخلي لـ Nginx
  type: NodePort       # يسمح بالوصول للموقع عبر localhost